### ISSUE TITLE
Cannot compile the solidity files with Truffle v4.1.15 : Solidity v0.4.25 (solc-js)

### ISSUE THREAD

**Issue by ecouffes** [truffle-box/metacoin-box#12]
**Issue**
The solidity files cannot be compiled with Truffle v4.1.15: solc-js compiler version 0.4.25, 
due to the PR https://github.com/truffle-box/metacoin-box/pull/11/files: updating the pragma.

**Environment**
- Truffle v4.1.15 (core: 4.1.15)
- Solidity v0.4.25 (solc-js)

**Proposal**
Fix the solidity version as described below: 
`pragma solidity >=0.4.25 <0.6.0;`

Truffle v4.1.15 is maintenance version of the Truffle v4.
Truffle have released this version in order to allow users of v4 to continue to use truffle unbox and truffle init.
Therefore, i think Metacoin-box had better support Truffle v4.1.15.

https://github.com/trufflesuite/truffle/releases/tag/v4.1.15

**Comment by adrianmcli** [comment]
Fixed by #13
